export const seoContent = {
  ar: {
    navLabel: "المدونة",
    blog: {
      eyebrow: "المدونة القانونية",
      title: "أسئلة قانونية شائعة في عمان",
      text: "محتوى مبني على أسئلة عملية يطرحها الأفراد وأصحاب الأعمال عند البحث عن محام أو استشارة قانونية في سلطنة عمان.",
      search: "ابحث عن طلاق، ميراث، شركة، عقد، عمال، ديون...",
      readMore: "اقرأ المزيد",
      consult: "استشارة",
      categories: [
        { key: "all", label: "الكل" },
        { key: "family", label: "الأحوال الشخصية" },
        { key: "business", label: "الشركات والعقود" },
        { key: "employment", label: "العمل" },
        { key: "real-estate", label: "العقارات" },
        { key: "disputes", label: "النزاعات والتنفيذ" },
      ],
      posts: [
        {
          category: "family",
          categoryLabel: "الأحوال الشخصية",
          title: "محامي طلاق في عمان: ما الخطوات الأولى قبل رفع الدعوى؟",
          excerpt: "قبل البدء في دعوى الطلاق أو النفقة أو الحضانة، من المهم ترتيب المستندات وفهم الاختصاص والمحكمة المناسبة والطلبات الممكنة.",
          date: "2026",
          keywords: ["محامي طلاق في عمان", "قضايا الحضانة", "النفقة في عمان"],
        },
        {
          category: "family",
          categoryLabel: "الأحوال الشخصية",
          title: "كيف يتم تقسيم الميراث في سلطنة عمان؟",
          excerpt: "قضايا الإرث تحتاج إلى حصر الورثة، تحديد التركة، معالجة الديون والوصايا، ثم اتخاذ الإجراءات المناسبة أمام الجهات المختصة.",
          date: "2026",
          keywords: ["تقسيم الميراث في عمان", "حصر الورثة", "محامي ميراث"],
        },
        {
          category: "business",
          categoryLabel: "الشركات والعقود",
          title: "تأسيس شركة في عمان: متى تحتاج إلى محام؟",
          excerpt: "وجود محام يساعد في اختيار الشكل القانوني، صياغة اتفاق الشركاء، مراجعة الالتزامات، وتقليل النزاعات بين الشركاء لاحقا.",
          date: "2026",
          keywords: ["تأسيس شركة في عمان", "محامي شركات", "اتفاق الشركاء"],
        },
        {
          category: "business",
          categoryLabel: "الشركات والعقود",
          title: "مراجعة عقد تجاري في عمان قبل التوقيع",
          excerpt: "أهم البنود التي تستحق المراجعة تشمل الصلاحيات، مدة العقد، المسؤولية، الجزاءات، الإنهاء، السرية، وآلية حل النزاع.",
          date: "2026",
          keywords: ["مراجعة عقد", "صياغة عقود", "محامي عقود في عمان"],
        },
        {
          category: "employment",
          categoryLabel: "قانون العمل",
          title: "منازعات العمل في عمان: ماذا يفعل العامل أو صاحب العمل؟",
          excerpt: "يفضل جمع عقد العمل، كشوف الرواتب، المخاطبات، وقرارات الإنذار أو الفصل قبل تقييم المسار القانوني المناسب.",
          date: "2026",
          keywords: ["قضايا عمالية عمان", "محامي عمال", "فصل تعسفي"],
        },
        {
          category: "real-estate",
          categoryLabel: "العقارات",
          title: "نزاع عقد إيجار في عمان: كيف تبدأ؟",
          excerpt: "تقييم عقد الإيجار، الإشعارات، المبالغ المستحقة، وحالة العقار يساعد في تحديد أفضل مسار للتسوية أو المطالبة.",
          date: "2026",
          keywords: ["نزاع إيجار عمان", "محامي عقارات", "عقد إيجار"],
        },
        {
          category: "disputes",
          categoryLabel: "النزاعات والتنفيذ",
          title: "تحصيل الديون في عمان: ما الخيارات القانونية؟",
          excerpt: "قد تبدأ المطالبة بإنذار قانوني أو تفاوض، وقد تنتقل إلى دعوى أو إجراءات تنفيذ بحسب المستندات وحالة المدين.",
          date: "2026",
          keywords: ["تحصيل ديون عمان", "تنفيذ أحكام", "مطالبة مالية"],
        },
        {
          category: "disputes",
          categoryLabel: "النزاعات والتنفيذ",
          title: "كيف أرفع دعوى في عمان؟",
          excerpt: "رفع الدعوى يتطلب تحديد الاختصاص، تجهيز المستندات، صياغة الطلبات، وسداد الرسوم المقررة حسب نوع القضية.",
          date: "2026",
          keywords: ["رفع دعوى في عمان", "محامي قضايا", "إجراءات المحاكم"],
        },
        {
          category: "business",
          categoryLabel: "دليل الشركات",
          title: "دليل قانوني لتأسيس شركة في سلطنة عمان",
          excerpt: "تأسيس الشركة لا يبدأ بالنموذج الإلكتروني فقط، بل يبدأ بفهم النشاط، الشركاء، الصلاحيات، المخاطر، والعقود التي ستنظم المشروع.",
          date: "2026",
          keywords: ["تأسيس شركة في سلطنة عمان", "محامي تأسيس شركات", "الشكل القانوني للشركة"],
          sections: [
            "قبل التسجيل، يجب تحديد النشاط التجاري بدقة ومعرفة ما إذا كان يحتاج موافقات أو تراخيص خاصة من جهات مختصة.",
            "اختيار الشكل القانوني يؤثر في مسؤولية الشركاء، الإدارة، دخول المستثمرين، توزيع الأرباح، وإجراءات الخروج من الشركة.",
            "ينصح بإعداد اتفاق شركاء مبكر يحدد صلاحيات المدير، التصويت، تمويل الشركة، توزيع الأرباح، منع المنافسة، وحل النزاعات.",
            "بعد التأسيس، تحتاج الشركة إلى نماذج عقود أساسية مثل عقود العملاء، الموردين، الموظفين، السرية، وسياسات الامتثال الداخلي.",
          ],
        },
        {
          category: "business",
          categoryLabel: "حوكمة الشركات",
          title: "اتفاق الشركاء في عمان: لماذا هو أهم من عقد التأسيس وحده؟",
          excerpt: "اتفاق الشركاء يحوّل التفاهمات الشفهية إلى قواعد واضحة تحمي الشركة عند الخلاف، التوسع، دخول مستثمر، أو خروج أحد الشركاء.",
          date: "2026",
          keywords: ["اتفاق الشركاء عمان", "نزاع بين الشركاء", "حوكمة الشركات"],
          sections: [
            "عقد التأسيس يحدد الإطار الرسمي، لكن اتفاق الشركاء يعالج التفاصيل اليومية التي تسبب معظم النزاعات التجارية.",
            "من أهم البنود: صلاحيات الإدارة، حدود التوقيع، القرارات التي تحتاج موافقة خاصة، آلية تقييم الحصص، وحقوق الأولوية.",
            "الاتفاق الجيد يتوقع السيناريوهات الصعبة مثل تعثر شريك في التمويل، وفاة شريك، بيع الحصص، أو تعطّل القرارات.",
            "وجود آلية واضحة للتسوية أو التحكيم أو الاختصاص القضائي يقلل تكلفة النزاع ويمنح الشركة فرصة للاستمرار.",
          ],
        },
        {
          category: "business",
          categoryLabel: "العقود التجارية",
          title: "مراجعة العقود التجارية في عمان: قائمة فحص قبل التوقيع",
          excerpt: "العقد التجاري القوي لا يكتفي بوصف الخدمة أو السعر، بل ينظم المخاطر والمسؤولية والدفع والإنهاء وحل النزاع.",
          date: "2026",
          keywords: ["مراجعة العقود في عمان", "محامي عقود تجارية", "صياغة عقد تجاري"],
          sections: [
            "تحقق من هوية الأطراف وصلاحية الموقّع، خاصة إذا كان الطرف شركة أو فرعا أو ممثلا تجاريا.",
            "راجع نطاق العمل والمخرجات ومواعيد التسليم ومعايير القبول حتى لا تتحول التفاصيل الفنية إلى نزاع قانوني.",
            "انتبه إلى حدود المسؤولية، التعويضات، غرامات التأخير، القوة القاهرة، السرية، وحقوق الملكية الفكرية.",
            "حدد القانون الواجب التطبيق وآلية حل النزاع والاختصاص، خصوصا في العقود التي تضم طرفا أجنبيا.",
          ],
        },
        {
          category: "business",
          categoryLabel: "الشركات الناشئة",
          title: "احتياجات الشركات الناشئة في عمان من المحامي",
          excerpt: "الشركة الناشئة تحتاج حماية قانونية مبكرة حتى لا تتحول السرعة في النمو إلى عقود ضعيفة أو نزاعات بين المؤسسين.",
          date: "2026",
          keywords: ["محامي شركات ناشئة", "استثمار في عمان", "حماية المؤسسين"],
          sections: [
            "في البداية، يحتاج المؤسسون إلى تنظيم الملكية والأدوار والالتزام بالتفرغ والتمويل وآلية الخروج.",
            "عند جذب مستثمر، تصبح بنود التقييم، الحصص، حقوق التصويت، التخفيف، المعلومات، والتخارج عناصر حساسة.",
            "ينبغي حماية الاسم التجاري والعلامة والأكواد والمحتوى والبيانات باتفاقيات واضحة مع الموظفين والمستقلين والموردين.",
            "نماذج العقود الجاهزة قد لا تناسب السوق العماني أو طبيعة النشاط، لذلك تحتاج مراجعة قبل استخدامها مع العملاء.",
          ],
        },
        {
          category: "employment",
          categoryLabel: "التوظيف والامتثال",
          title: "التزامات الشركات تجاه الموظفين في قانون العمل العماني",
          excerpt: "إدارة الموظفين قانونيا لا تعني عقد عمل فقط، بل ملفات عمال، لوائح داخلية، أجور، ساعات عمل، وسرية معلومات.",
          date: "2026",
          keywords: ["قانون العمل العماني", "التزامات صاحب العمل", "لوائح العمل"],
          sections: [
            "يلزم صاحب العمل عادة بتنظيم العلاقة كتابة وحفظ مستندات العامل والبيانات الأساسية والمراسلات المهمة.",
            "الشركات التي تكبر في عدد الموظفين تحتاج لوائح داخلية وسياسات جزاءات وشكاوى تتوافق مع المتطلبات النظامية.",
            "إدارة ساعات العمل والإجازات والعمل الإضافي تحتاج توثيقا واضحا حتى لا تتحول إلى مطالبات مالية لاحقة.",
            "أي إنهاء لعلاقة العمل يجب أن يراجع بعناية من حيث السبب والإجراءات والمستحقات والمستندات المؤيدة.",
          ],
        },
        {
          category: "business",
          categoryLabel: "الامتثال التجاري",
          title: "لماذا تحتاج الشركات في عمان إلى مراجعة قانونية دورية؟",
          excerpt: "المراجعة القانونية الدورية تساعد الإدارة على اكتشاف المخاطر قبل وصولها إلى نزاع أو غرامة أو تعطيل في النشاط.",
          date: "2026",
          keywords: ["مراجعة قانونية للشركات", "امتثال الشركات عمان", "إدارة المخاطر القانونية"],
          sections: [
            "تشمل المراجعة الدورية العقود النشطة، الالتزامات المالية، التراخيص، عقود العمل، النزاعات المحتملة، والديون المتأخرة.",
            "تساعد الإدارة على معرفة العقود التي تحتاج تجديدا أو إخطارا أو إعادة تفاوض قبل انتهاء المدد المهمة.",
            "الشركات التي تتعامل مع موردين وعملاء كثر تستفيد من توحيد نماذج العقود وشروط الدفع والتسليم والمسؤولية.",
            "الهدف ليس تعقيد العمل التجاري، بل جعل القرارات أسرع لأنها مبنية على معرفة واضحة بالمخاطر.",
          ],
        },
        {
          category: "disputes",
          categoryLabel: "تحصيل الديون التجارية",
          title: "تحصيل مستحقات الشركات في عمان: من المطالبة الودية إلى التنفيذ",
          excerpt: "التحصيل الفعّال يبدأ من توثيق الدين، ثم اختيار المسار المناسب بين المطالبة الودية، الإنذار، الدعوى، أو التنفيذ.",
          date: "2026",
          keywords: ["تحصيل مستحقات الشركات", "مطالبة مالية عمان", "إنذار قانوني"],
          sections: [
            "أقوى ملفات التحصيل هي التي تحتوي عقدا أو أمر شراء أو فاتورة معتمدة أو مراسلات تثبت التسليم أو الاستحقاق.",
            "الإنذار القانوني قد يكون مناسبا لإثبات الجدية ومنح الطرف الآخر فرصة للسداد أو التسوية قبل الدعوى.",
            "في بعض الحالات، تكون التسوية التجارية أفضل من النزاع الطويل إذا ضمنت جدولة واضحة وضمانات مقبولة.",
            "بعد صدور حكم أو سند قابل للتنفيذ، ينتقل التركيز إلى إجراءات التنفيذ ومتابعة الوفاء بالمبلغ.",
          ],
        },
        {
          category: "real-estate",
          categoryLabel: "العقار والإنشاءات",
          title: "العقود العقارية والإنشائية في عمان: نقاط قانونية لا ينبغي تجاهلها",
          excerpt: "مشاريع العقار والإنشاءات تحتاج عقودا واضحة في النطاق والدفعات والتغييرات والتأخير والضمانات وتسوية النزاعات.",
          date: "2026",
          keywords: ["عقود مقاولات عمان", "محامي عقارات عمان", "نزاعات إنشائية"],
          sections: [
            "في عقود المقاولات، يجب تحديد نطاق الأعمال والمواصفات والمخططات وآلية اعتماد التغييرات والأعمال الإضافية.",
            "جدول الدفعات يجب أن يرتبط بإنجازات واضحة أو مستندات اعتماد حتى لا تتراكم مطالبات غير محسومة.",
            "بنود التأخير والعيوب والضمانات مهمة لأنها تحدد المسؤولية بعد التسليم وخلال فترة الضمان.",
            "وجود آلية تسوية نزاع مناسبة يحمي المشروع من التوقف الكامل عند ظهور خلاف فني أو مالي.",
          ],
        },
        {
          category: "business",
          categoryLabel: "الملكية الفكرية",
          title: "حماية العلامة التجارية والأصول الفكرية للشركات في عمان",
          excerpt: "اسم الشركة وشعارها ومحتواها ومنتجاتها الرقمية أصول تجارية تحتاج حماية مبكرة مثلها مثل العقود والأموال.",
          date: "2026",
          keywords: ["تسجيل علامة تجارية في عمان", "حماية الملكية الفكرية", "أسرار تجارية"],
          sections: [
            "قبل إطلاق العلامة، يفضل البحث عن علامات مشابهة لتقليل مخاطر الاعتراض أو النزاع بعد الاستثمار في الهوية.",
            "العقود مع المصممين والمبرمجين والمستقلين يجب أن توضح ملكية الأعمال وحقوق الاستخدام والتعديل والتسليم.",
            "الأسرار التجارية تحتاج اتفاقيات سرية وسياسات وصول داخلية، خاصة للشركات التي تملك بيانات عملاء أو طرق تشغيل مميزة.",
            "عند حدوث تعد على العلامة أو المحتوى، يساعد التوثيق المبكر في تحديد مسار الإنذار أو المطالبة أو التسوية.",
          ],
        },
        {
          category: "business",
          categoryLabel: "العقود الدولية",
          title: "التعاقد مع شركة أجنبية من داخل عمان: ما الذي يجب الانتباه له؟",
          excerpt: "العقود الدولية تحتاج عناية خاصة في اللغة، القانون الواجب التطبيق، الضرائب، الدفع، العملة، الاختصاص، وتنفيذ الأحكام.",
          date: "2026",
          keywords: ["عقود دولية عمان", "شركة أجنبية", "قانون واجب التطبيق"],
          sections: [
            "حدد اللغة المعتمدة عند التعارض بين النص العربي والإنجليزي، لأن اختلاف الترجمة قد يغيّر الالتزامات العملية.",
            "راجع القانون الواجب التطبيق والاختصاص القضائي أو التحكيم، لأن ذلك يؤثر على تكلفة النزاع وإمكانية التنفيذ.",
            "بنود الدفع والعملة والتحويل والتأخير والضرائب يجب أن تكون واضحة حتى لا تظهر خلافات مالية عند التنفيذ.",
            "إذا كان العقد يتضمن بيانات أو ملكية فكرية أو توريدا عبر الحدود، فالأفضل مراجعة الالتزامات التنظيمية مبكرا.",
          ],
        },
        {
          category: "business",
          categoryLabel: "التجارة الإلكترونية",
          title: "المتاجر الإلكترونية في عمان: الشروط القانونية التي تحتاجها قبل البيع",
          excerpt: "المتجر الإلكتروني يحتاج شروط استخدام وسياسة خصوصية وسياسة إرجاع واضحة، إلى جانب عقود موردين وحماية علامة تجارية.",
          date: "2026",
          keywords: ["متجر إلكتروني عمان", "شروط وأحكام", "سياسة خصوصية"],
          sections: [
            "الشروط والأحكام تحدد طريقة الشراء والدفع والتوصيل والإرجاع وحدود المسؤولية عند التأخير أو الخطأ.",
            "سياسة الخصوصية تساعد العميل على فهم كيفية استخدام بياناته، وهي مهمة لبناء الثقة وتقليل المخاطر.",
            "عقود الموردين وشركات التوصيل يجب أن توضح المسؤولية عند تلف المنتج أو تأخر الشحنة أو رفض العميل للاستلام.",
            "حماية العلامة والمحتوى والصور ووصف المنتجات تمنع التقليد وتدعم موقف المتجر عند ظهور منافسة غير عادلة.",
          ],
        },
        {
          category: "business",
          categoryLabel: "إدارة المخاطر",
          title: "متى يجب على صاحب العمل الاتصال بمحام قبل اتخاذ قرار تجاري؟",
          excerpt: "بعض القرارات تبدو تجارية بحتة، لكنها تحمل أثرا قانونيا كبيرا مثل إنهاء عقد، فصل موظف، قبول مستثمر، أو إرسال إنذار.",
          date: "2026",
          keywords: ["استشارة قانونية للشركات", "قرارات تجارية", "مخاطر قانونية"],
          sections: [
            "اتصل بمحام قبل إنهاء عقد مهم أو تغيير شروط جوهرية أو وقف توريد أو مطالبة عميل بمبالغ كبيرة.",
            "استشر قبل فصل موظف أو خصم مستحقات أو تعديل وظيفة إذا كانت المستندات أو الإجراءات غير مكتملة.",
            "عند دخول شريك أو مستثمر، يجب توثيق التقييم والحقوق والصلاحيات والتخارج قبل استلام الأموال أو نقل الحصص.",
            "الاستشارة المبكرة غالبا أقل تكلفة من معالجة نزاع بدأ بسبب رسالة أو قرار غير محسوب.",
          ],
        },
      ],
    },
    faq: {
      eyebrow: "أسئلة متكررة",
      title: "إجابات مختصرة لأسئلة يبحث عنها العملاء",
      text: "إجابات عامة تساعد الزائر على فهم الخطوة الأولى. لا تغني عن استشارة قانونية مخصصة.",
      items: [
        {
          question: "كيف أختار أفضل محامي في عمان؟",
          answer: "ابحث عن محام لديه خبرة في نوع قضيتك، تواصل واضح، تقدير واقعي للمخاطر، واتفاق مكتوب يوضح نطاق العمل والأتعاب.",
        },
        {
          question: "كم أتعاب المحامي في عمان؟",
          answer: "تختلف الأتعاب حسب نوع القضية، حجم المستندات، درجة التعقيد، والوقت المتوقع. الأفضل طلب عرض مكتوب بعد شرح الوقائع والمستندات.",
        },
        {
          question: "هل يمكن الحصول على استشارة قانونية عبر واتساب؟",
          answer: "يمكن استخدام واتساب للتواصل الأولي وتحديد موعد، لكن الرأي القانوني الدقيق يحتاج غالبا إلى مراجعة المستندات وتأكيد الوقائع.",
        },
        {
          question: "ما المستندات المطلوبة لرفع دعوى؟",
          answer: "تختلف حسب نوع الدعوى، لكنها غالبا تشمل الهوية، العقود أو المراسلات، الأدلة المالية، الإنذارات، وأي مستند يثبت المطالبة.",
        },
        {
          question: "هل التسوية أفضل من المحكمة؟",
          answer: "التسوية قد تكون أفضل إذا وفرت الوقت والتكلفة وحافظت على العلاقة التجارية، لكن القرار يعتمد على قوة الأدلة وموقف الطرف الآخر.",
        },
        {
          question: "متى أحتاج محامي شركات في عمان؟",
          answer: "تحتاجه عند تأسيس شركة، دخول شريك جديد، صياغة عقد تجاري، مراجعة التزام تنظيمي، أو حدوث نزاع بين الشركاء.",
        },
        {
          question: "كيف أطالب بدين أو مبلغ مستحق؟",
          answer: "ابدأ بجمع الفواتير والعقود والمراسلات، ثم يمكن إرسال إنذار قانوني أو تقييم خيار الدعوى والتنفيذ بحسب قوة المستندات.",
        },
        {
          question: "هل محتوى الموقع يعتبر استشارة قانونية؟",
          answer: "لا. المحتوى للتوعية العامة فقط، ولا يعد استشارة قانونية أو علاقة محام وموكل إلا بعد قبول المكتب للتمثيل كتابة.",
        },
        {
          question: "ما الفرق بين الاستشارة القانونية والتمثيل أمام المحكمة؟",
          answer: "الاستشارة القانونية توضح الموقف والخيارات والمخاطر، أما التمثيل أمام المحكمة فيشمل إعداد الملف والمذكرات ومتابعة الجلسات والإجراءات.",
        },
        {
          question: "هل أحتاج محامي قبل توقيع عقد إيجار أو بيع عقار؟",
          answer: "يفضل مراجعة العقد قبل التوقيع للتأكد من الصلاحيات، وصف العقار، الالتزامات، شروط الدفع، الإنهاء، والتعويض عند الإخلال.",
        },
        {
          question: "كيف أتعامل مع شيك مرتجع في عمان؟",
          answer: "ينبغي حفظ أصل الشيك وإشعار البنك والمراسلات، ثم تقييم المسار القانوني المناسب للمطالبة بالمبلغ أو اتخاذ الإجراءات المتاحة.",
        },
        {
          question: "ما مدة القضايا في المحاكم العمانية؟",
          answer: "تختلف المدة حسب نوع القضية، عدد الخصوم، حجم المستندات، الخبرة الفنية، والاستئناف. يمكن للمحامي تقديم تقدير أولي بعد مراجعة الملف.",
        },
        {
          question: "هل يمكن حل النزاع التجاري بدون رفع دعوى؟",
          answer: "نعم، يمكن البدء بالتفاوض أو الإنذار القانوني أو الوساطة أو التسوية، خصوصا إذا كان الطرفان يرغبان في حفظ العلاقة التجارية.",
        },
        {
          question: "متى أحتاج إلى إنذار قانوني؟",
          answer: "يستخدم الإنذار القانوني لإثبات المطالبة أو طلب تنفيذ التزام أو منح الطرف الآخر فرصة أخيرة قبل اتخاذ إجراءات قضائية.",
        },
        {
          question: "ما حقوق العامل عند إنهاء عقد العمل؟",
          answer: "تعتمد الحقوق على نوع العقد وسبب الإنهاء ومدة الخدمة والمستحقات غير المدفوعة. يجب مراجعة العقد والرواتب والمراسلات قبل تحديد المطالبة.",
        },
        {
          question: "ماذا أفعل إذا تم فصلي من العمل؟",
          answer: "احتفظ بخطاب الفصل وعقد العمل وكشوف الرواتب وأي رسائل مرتبطة بالقرار، ثم اطلب تقييما قانونيا لمعرفة الخيارات المتاحة.",
        },
        {
          question: "كيف أحمي علامتي التجارية في عمان؟",
          answer: "ابدأ بالبحث عن العلامات المشابهة، ثم قدّم طلب التسجيل المناسب، واحتفظ بأدلة الاستخدام لمواجهة أي تعد أو اعتراض.",
        },
        {
          question: "هل يمكن صياغة العقود باللغتين العربية والإنجليزية؟",
          answer: "نعم، ويمكن تحديد اللغة المعتمدة عند التعارض. الصياغة الثنائية مفيدة للمعاملات التي تضم أطرافا محلية ودولية.",
        },
        {
          question: "ما أهمية اتفاق الشركاء في الشركات؟",
          answer: "ينظم اتفاق الشركاء الإدارة، توزيع الأرباح، نقل الحصص، الخروج من الشركة، وحل النزاعات قبل تحولها إلى خلافات مكلفة.",
        },
        {
          question: "كيف أتعامل مع نزاع بين شركاء؟",
          answer: "ابدأ بمراجعة عقد التأسيس واتفاق الشركاء والمراسلات والقرارات المالية، ثم قيّم خيارات التفاوض أو التسوية أو الدعوى.",
        },
        {
          question: "هل التحكيم مناسب لكل النزاعات التجارية؟",
          answer: "ليس دائما. التحكيم قد يكون مناسبا للعقود الكبيرة أو المتخصصة، لكنه يحتاج شرط تحكيم واضحا وتقييما للتكلفة والوقت وقابلية التنفيذ.",
        },
        {
          question: "ما المقصود بتنفيذ الأحكام؟",
          answer: "تنفيذ الأحكام هو مرحلة مطالبة الطرف المحكوم عليه بالوفاء بما قضى به الحكم، وفق إجراءات التنفيذ والضمانات النظامية.",
        },
        {
          question: "هل يمكن الاعتراض على حكم قضائي؟",
          answer: "غالبا توجد طرق اعتراض محددة بمدد وإجراءات، مثل الاستئناف بحسب نوع الحكم. يجب مراجعة تاريخ الحكم وأسبابه بسرعة.",
        },
        {
          question: "ما حقوق المستأجر والمؤجر عند التأخر في دفع الإيجار؟",
          answer: "تعتمد الحقوق على عقد الإيجار والإشعارات والمبالغ المستحقة. يجب توثيق المطالبة ومراجعة شروط الإنهاء أو المطالبة المالية.",
        },
        {
          question: "هل يحتاج الوافد إلى محام في القضايا داخل عمان؟",
          answer: "قد يحتاج الوافد إلى محام لفهم الإجراءات واللغة والمستندات المطلوبة، خاصة في قضايا العمل، العقود، الأسرة، أو المطالبات المالية.",
        },
        {
          question: "ما الخطوة الأولى في قضايا الحضانة؟",
          answer: "الخطوة الأولى هي تحديد الطلبات وجمع المستندات المتعلقة بالأطفال والنفقة والسكن والرعاية، ثم تقييم المسار الأنسب للمحكمة أو التسوية.",
        },
        {
          question: "كيف أجهز ملفي قبل مقابلة المحامي؟",
          answer: "رتب الوقائع زمنيا، واجمع العقود والمراسلات والإيصالات والأحكام السابقة، واكتب الأسئلة الرئيسية التي تريد الإجابة عنها.",
        },
        {
          question: "هل يمكن مراجعة عقد أرسلته شركة أجنبية؟",
          answer: "نعم، ويمكن مراجعته من ناحية التزامات الطرف العماني، القانون الواجب التطبيق، الاختصاص، الدفع، السرية، والإنهاء.",
        },
        {
          question: "ما أول خطوة لتأسيس شركة في عمان؟",
          answer: "تبدأ الخطوة الأولى بتحديد النشاط والشركاء والشكل القانوني المناسب، ثم مراجعة المتطلبات النظامية والعقود الأساسية قبل التسجيل.",
        },
        {
          question: "ما أفضل شكل قانوني للشركة الجديدة؟",
          answer: "يعتمد الشكل القانوني على عدد الشركاء، طبيعة النشاط، حجم المسؤولية، رأس المال، وخطة التوسع. لذلك يفضل تقييمه قبل التسجيل.",
        },
        {
          question: "هل أحتاج اتفاق شركاء إذا كانت الشركة بين أقارب أو أصدقاء؟",
          answer: "نعم، فالعلاقة الشخصية لا تكفي لحماية الشركة. اتفاق الشركاء ينظم الإدارة، الأرباح، الخروج، وفاة الشريك، وطرق حل الخلاف.",
        },
        {
          question: "ما البنود المهمة في عقد الشراكة التجارية؟",
          answer: "تشمل البنود المهمة رأس المال، الإدارة، الصلاحيات، توزيع الأرباح، منع المنافسة، سرية المعلومات، الانسحاب، وتسوية النزاعات.",
        },
        {
          question: "متى تحتاج الشركة إلى مستشار قانوني دائم؟",
          answer: "تحتاج الشركة إلى مستشار قانوني دائم عند وجود عقود متكررة، موظفين، موردين، ديون، توسع تجاري، أو قرارات تحتاج مراجعة مخاطر مستمرة.",
        },
        {
          question: "كيف يحمي المحامي الشركة من النزاعات التجارية؟",
          answer: "يساعد المحامي في صياغة عقود واضحة، توثيق القرارات، وضع سياسات داخلية، مراجعة المخاطر، والتدخل المبكر قبل تصاعد الخلاف.",
        },
        {
          question: "ما المستندات المطلوبة لمراجعة وضع الشركة القانوني؟",
          answer: "غالبا تشمل السجل التجاري، عقد التأسيس، اتفاق الشركاء، التراخيص، العقود الرئيسية، عقود العمل، الالتزامات المالية، والمراسلات المهمة.",
        },
        {
          question: "هل تحتاج الشركة إلى مراجعة قانونية قبل توقيع عقد توريد؟",
          answer: "نعم، لأن عقود التوريد تتضمن غالبا مواعيد تسليم، جودة، ضمانات، غرامات تأخير، شروط دفع، ومسؤولية عند الإخلال.",
        },
        {
          question: "كيف تتعامل الشركة مع عميل لا يدفع المستحقات؟",
          answer: "ينبغي جمع الفواتير والعقد وأوامر الشراء والمراسلات، ثم إرسال مطالبة أو إنذار قانوني وتقييم مسار التحصيل أو التسوية.",
        },
        {
          question: "ما أهمية الشروط والأحكام للشركات التي تبيع عبر الإنترنت؟",
          answer: "الشروط والأحكام توضح سياسة البيع، الدفع، الإرجاع، المسؤولية، الخصوصية، وتسوية النزاعات، وتقلل سوء الفهم مع العملاء.",
        },
        {
          question: "هل تحتاج الشركات الناشئة إلى محام منذ البداية؟",
          answer: "وجود محام منذ البداية يساعد في حماية الملكية الفكرية، تنظيم العلاقة بين المؤسسين، مراجعة الاستثمار، وصياغة عقود العملاء والموردين.",
        },
        {
          question: "كيف يتم التعامل مع خروج شريك من الشركة؟",
          answer: "يجب مراجعة عقد التأسيس واتفاق الشركاء لتحديد آلية التقييم، نقل الحصص، الالتزامات، السرية، وعدم المنافسة بعد الخروج.",
        },
        {
          question: "ما الذي يجب مراجعته قبل دخول مستثمر جديد؟",
          answer: "ينبغي مراجعة تقييم الشركة، نسبة الحصص، حقوق التصويت، الإدارة، التزامات المؤسسين، التخارج، وحماية المعلومات السرية.",
        },
        {
          question: "هل يمكن للشركة توحيد نماذج العقود لتقليل المخاطر؟",
          answer: "نعم، إعداد نماذج عقود موحدة للمبيعات، التوريد، الخدمات، التوظيف، والسرية يساعد على تقليل الأخطاء وتسريع التعاملات.",
        },
        {
          question: "متى تحتاج الشركة إلى سياسة داخلية مكتوبة؟",
          answer: "تحتاجها عند وجود موظفين أو عمليات متكررة أو بيانات حساسة أو صلاحيات مالية، حتى تكون القرارات واضحة وقابلة للتطبيق.",
        },
        {
          question: "كيف تحمي الشركة أسرارها التجارية؟",
          answer: "يمكن حماية الأسرار التجارية بعقود سرية، تقييد الوصول للمعلومات، سياسات داخلية، وبنود واضحة في عقود الموظفين والموردين.",
        },
        {
          question: "ما مخاطر توقيع عقد تجاري بدون مراجعة قانونية؟",
          answer: "قد تظهر مخاطر في المسؤولية، الجزاءات، الاختصاص، الإنهاء، الدفع، أو الالتزامات غير الواضحة، وقد يصعب تعديلها بعد التوقيع.",
        },
        {
          question: "هل يمكن للمحامي حضور مفاوضات تجارية؟",
          answer: "نعم، حضور المحامي يساعد في حماية الموقف القانوني أثناء التفاوض وتوثيق النقاط الجوهرية قبل تحويلها إلى عقد نهائي.",
        },
        {
          question: "ما احتياجات الشركات الصغيرة من الخدمات القانونية؟",
          answer: "غالبا تحتاج الشركات الصغيرة إلى عقود عمل، عقود عملاء وموردين، تحصيل مستحقات، حماية علامة تجارية، واستشارات عند النزاعات.",
        },
        {
          question: "كيف تساعد الاستشارة القانونية في نمو الشركة؟",
          answer: "الاستشارة القانونية الجيدة تقلل المخاطر، توضح الالتزامات، تحسن العقود، وتحمي الشركة أثناء التوسع أو الدخول في شراكات جديدة.",
        },
      ],
    },
  },
  en: {
    navLabel: "Blog",
    blog: {
      eyebrow: "Legal Blog",
      title: "Common legal questions in Oman",
      text: "Practical content shaped around questions individuals and businesses ask when searching for a lawyer or legal advice in Oman.",
      search: "Search divorce, inheritance, company, contract, labour, debt...",
      readMore: "Read more",
      consult: "Consultation",
      categories: [
        { key: "all", label: "All" },
        { key: "family", label: "Family" },
        { key: "business", label: "Business" },
        { key: "employment", label: "Employment" },
        { key: "real-estate", label: "Real estate" },
        { key: "disputes", label: "Disputes" },
      ],
      posts: [
        {
          category: "family",
          categoryLabel: "Family law",
          title: "Divorce lawyer in Oman: what should you prepare first?",
          excerpt: "Before filing for divorce, maintenance, or custody, organise key documents and understand jurisdiction, claims, and expected procedure.",
          date: "2026",
          keywords: ["divorce lawyer Oman", "custody cases", "maintenance in Oman"],
        },
        {
          category: "family",
          categoryLabel: "Inheritance",
          title: "How is inheritance handled in Oman?",
          excerpt: "Inheritance matters often require identifying heirs, listing estate assets, reviewing debts and wills, then taking the right procedural steps.",
          date: "2026",
          keywords: ["inheritance in Oman", "heirs certificate", "inheritance lawyer"],
        },
        {
          category: "business",
          categoryLabel: "Companies",
          title: "Company formation in Oman: when do you need a lawyer?",
          excerpt: "A lawyer can help with legal form, shareholders’ agreements, obligations, and preventing future partner disputes.",
          date: "2026",
          keywords: ["company formation Oman", "corporate lawyer Oman", "shareholders agreement"],
        },
        {
          category: "business",
          categoryLabel: "Contracts",
          title: "Reviewing a commercial contract in Oman before signing",
          excerpt: "Authority, term, liability, penalties, termination, confidentiality, and dispute resolution should be reviewed before signing.",
          date: "2026",
          keywords: ["contract review Oman", "contract lawyer Oman", "commercial agreement"],
        },
        {
          category: "employment",
          categoryLabel: "Employment",
          title: "Labour disputes in Oman: what should employees and employers do?",
          excerpt: "Collect the employment contract, salary records, correspondence, and warning or termination letters before choosing a legal path.",
          date: "2026",
          keywords: ["labour case Oman", "employment lawyer Oman", "unfair dismissal"],
        },
        {
          category: "real-estate",
          categoryLabel: "Real estate",
          title: "Lease dispute in Oman: where should you start?",
          excerpt: "Review the lease, notices, unpaid amounts, and property condition before deciding whether to settle or claim.",
          date: "2026",
          keywords: ["lease dispute Oman", "real estate lawyer Oman", "rental contract"],
        },
        {
          category: "disputes",
          categoryLabel: "Debt recovery",
          title: "Debt recovery in Oman: what legal options are available?",
          excerpt: "A claim may start with a legal notice or negotiation and move to litigation or enforcement depending on the documents and debtor position.",
          date: "2026",
          keywords: ["debt recovery Oman", "enforcement Oman", "financial claim"],
        },
        {
          category: "disputes",
          categoryLabel: "Litigation",
          title: "How do I file a court case in Oman?",
          excerpt: "Filing requires identifying jurisdiction, preparing documents, drafting claims, and paying applicable fees according to the case type.",
          date: "2026",
          keywords: ["file case Oman", "litigation lawyer Oman", "court procedures"],
        },
        {
          category: "business",
          categoryLabel: "Company guide",
          title: "Legal guide to company formation in Oman",
          excerpt: "Company formation starts before online registration, with activity choice, partners, authority, risks, and contracts that govern the venture.",
          date: "2026",
          keywords: ["company formation in Oman", "company lawyer Oman", "legal structure"],
          sections: [
            "Before registration, define the commercial activity carefully and check whether special approvals or licences are required.",
            "The legal structure affects partner liability, management, investor entry, profit distribution, and exit procedures.",
            "An early shareholders’ agreement should address manager authority, voting, company funding, profits, non-compete, and dispute resolution.",
            "After formation, companies need basic templates such as customer contracts, supplier contracts, employment contracts, NDAs, and compliance policies.",
          ],
        },
        {
          category: "business",
          categoryLabel: "Corporate governance",
          title: "Shareholders’ agreements in Oman: why incorporation documents are not enough",
          excerpt: "A shareholders’ agreement turns informal understandings into clear rules for disputes, expansion, investor entry, and partner exits.",
          date: "2026",
          keywords: ["shareholders agreement Oman", "partner dispute", "corporate governance"],
          sections: [
            "Incorporation documents provide the official framework, but shareholders’ agreements address daily details that often create disputes.",
            "Important clauses include management powers, signing limits, reserved matters, share valuation, and pre-emption rights.",
            "A strong agreement anticipates difficult scenarios such as funding default, death of a partner, share sale, or management deadlock.",
            "A clear settlement, arbitration, or jurisdiction clause can reduce dispute cost and help the company continue operating.",
          ],
        },
        {
          category: "business",
          categoryLabel: "Commercial contracts",
          title: "Commercial contract review in Oman: checklist before signing",
          excerpt: "A strong commercial contract does more than describe service and price; it allocates risk, liability, payment, termination, and dispute handling.",
          date: "2026",
          keywords: ["contract review Oman", "commercial contract lawyer", "draft commercial contract"],
          sections: [
            "Check party identity and signing authority, especially when the other party is a company, branch, or commercial representative.",
            "Review scope of work, deliverables, delivery dates, and acceptance criteria so technical details do not become legal disputes.",
            "Pay attention to liability limits, indemnities, delay penalties, force majeure, confidentiality, and intellectual property rights.",
            "Define governing law, dispute resolution, and jurisdiction, especially when the contract includes a foreign party.",
          ],
        },
        {
          category: "business",
          categoryLabel: "Startups",
          title: "What legal support do startups in Oman need?",
          excerpt: "Startups need early legal protection so fast growth does not create weak contracts or founder disputes.",
          date: "2026",
          keywords: ["startup lawyer Oman", "investment Oman", "founder protection"],
          sections: [
            "Founders should regulate ownership, roles, full-time commitment, funding, and exit mechanisms from the beginning.",
            "When raising investment, valuation, share percentage, voting rights, dilution, information rights, and exit terms become sensitive.",
            "Names, trademarks, code, content, and data should be protected through clear agreements with employees, freelancers, and suppliers.",
            "Generic templates may not fit the Omani market or the business model, so they should be reviewed before use with customers.",
          ],
        },
        {
          category: "employment",
          categoryLabel: "Employment compliance",
          title: "Company obligations toward employees under Omani labour law",
          excerpt: "Employment compliance is more than a contract; it includes worker files, internal regulations, wages, working hours, and confidentiality.",
          date: "2026",
          keywords: ["Omani labour law", "employer obligations", "workplace policies"],
          sections: [
            "Employers usually need to document the relationship and retain employee data, key records, and important correspondence.",
            "Growing companies may need internal regulations, disciplinary policies, and grievance systems aligned with legal requirements.",
            "Working hours, leave, and overtime should be documented clearly to prevent later financial claims.",
            "Termination should be reviewed carefully for reason, procedure, dues, and supporting documents.",
          ],
        },
        {
          category: "business",
          categoryLabel: "Commercial compliance",
          title: "Why companies in Oman need periodic legal reviews",
          excerpt: "A periodic legal review helps management detect risks before they become disputes, penalties, or operational disruption.",
          date: "2026",
          keywords: ["company legal review", "corporate compliance Oman", "legal risk management"],
          sections: [
            "A review can cover active contracts, financial obligations, licences, employment contracts, potential disputes, and overdue debts.",
            "It helps management identify contracts that need renewal, notice, or renegotiation before key deadlines pass.",
            "Companies dealing with many customers and suppliers benefit from standardising contract templates, payment terms, delivery terms, and liability clauses.",
            "The goal is not to slow business down, but to make decisions faster because risks are visible.",
          ],
        },
        {
          category: "disputes",
          categoryLabel: "Commercial debt recovery",
          title: "Recovering company receivables in Oman: from demand to enforcement",
          excerpt: "Effective recovery starts with proving the debt, then choosing between friendly demand, legal notice, litigation, or enforcement.",
          date: "2026",
          keywords: ["company debt recovery Oman", "financial claim Oman", "legal notice"],
          sections: [
            "The strongest recovery files include a contract, purchase order, approved invoice, or correspondence proving delivery or entitlement.",
            "A legal notice may record seriousness and give the other party an opportunity to pay or settle before litigation.",
            "In some cases, a commercial settlement is better than a long dispute if it includes a clear payment schedule and acceptable safeguards.",
            "After a judgment or enforceable instrument, the focus shifts to enforcement procedures and follow-up on payment.",
          ],
        },
        {
          category: "real-estate",
          categoryLabel: "Real estate and construction",
          title: "Real estate and construction contracts in Oman: legal points not to miss",
          excerpt: "Real estate and construction projects need clear contracts on scope, payments, variations, delay, warranties, and dispute resolution.",
          date: "2026",
          keywords: ["construction contracts Oman", "real estate lawyer Oman", "construction disputes"],
          sections: [
            "Construction contracts should define scope, specifications, drawings, and approval mechanisms for variations and additional works.",
            "Payment schedules should be linked to clear milestones or approval documents to avoid unresolved claims.",
            "Delay, defects, and warranty clauses are important because they define responsibility after delivery and during the warranty period.",
            "A suitable dispute mechanism can protect the project from full stoppage when a technical or financial disagreement arises.",
          ],
        },
        {
          category: "business",
          categoryLabel: "Intellectual property",
          title: "Protecting trademarks and intellectual assets for companies in Oman",
          excerpt: "A company name, logo, content, and digital products are commercial assets that need early protection just like contracts and money.",
          date: "2026",
          keywords: ["trademark registration Oman", "intellectual property protection", "trade secrets"],
          sections: [
            "Before launching a brand, search for similar marks to reduce objection or dispute risk after investing in the identity.",
            "Contracts with designers, developers, and freelancers should clarify ownership, usage rights, modification rights, and delivery.",
            "Trade secrets need NDAs and internal access policies, especially for companies with customer data or unique operating methods.",
            "If infringement occurs, early documentation helps determine whether to send a notice, claim, or negotiate settlement.",
          ],
        },
        {
          category: "business",
          categoryLabel: "International contracts",
          title: "Contracting with a foreign company from Oman: what should you watch for?",
          excerpt: "International contracts need care with language, governing law, tax, payment, currency, jurisdiction, and enforcement.",
          date: "2026",
          keywords: ["international contracts Oman", "foreign company", "governing law"],
          sections: [
            "State which language prevails if Arabic and English texts conflict, because translation differences may change practical obligations.",
            "Review governing law and court jurisdiction or arbitration because they affect dispute cost and enforceability.",
            "Payment, currency, transfer, delay, and tax clauses should be clear to prevent financial disputes during performance.",
            "If the contract involves data, intellectual property, or cross-border supply, regulatory obligations should be reviewed early.",
          ],
        },
        {
          category: "business",
          categoryLabel: "E-commerce",
          title: "E-commerce businesses in Oman: legal terms needed before selling",
          excerpt: "An online store needs terms of use, privacy policy, return policy, supplier contracts, and brand protection.",
          date: "2026",
          keywords: ["e-commerce Oman", "terms and conditions", "privacy policy"],
          sections: [
            "Terms and conditions define purchase, payment, delivery, returns, and liability for delay or error.",
            "A privacy policy helps customers understand data use and supports trust while reducing legal risk.",
            "Supplier and delivery company contracts should address responsibility for damaged goods, shipment delay, and refusal to accept delivery.",
            "Protecting the brand, content, images, and product descriptions helps address imitation and unfair competition.",
          ],
        },
        {
          category: "business",
          categoryLabel: "Risk management",
          title: "When should a business owner contact a lawyer before making a commercial decision?",
          excerpt: "Some decisions look purely commercial but carry legal consequences, such as ending a contract, dismissing an employee, accepting an investor, or sending a notice.",
          date: "2026",
          keywords: ["business legal advice Oman", "commercial decisions", "legal risk"],
          sections: [
            "Contact a lawyer before terminating an important contract, changing key terms, stopping supply, or claiming large amounts from a customer.",
            "Seek advice before dismissing an employee, deducting dues, or changing a role if the documents or process are incomplete.",
            "When adding a partner or investor, valuation, rights, authority, and exit should be documented before receiving funds or transferring shares.",
            "Early advice is often less costly than fixing a dispute that began with an unreviewed message or decision.",
          ],
        },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "Short answers to high-intent legal searches",
      text: "General answers that help visitors understand the first step. They are not a substitute for tailored legal advice.",
      items: [
        {
          question: "How do I choose the best lawyer in Oman?",
          answer: "Look for experience in your type of matter, clear communication, realistic risk assessment, and a written scope of work and fee arrangement.",
        },
        {
          question: "How much does a lawyer cost in Oman?",
          answer: "Fees vary by matter type, document volume, complexity, and expected time. Ask for a written proposal after sharing the facts and documents.",
        },
        {
          question: "Can I get legal advice through WhatsApp?",
          answer: "WhatsApp can be used for initial contact and appointments, but accurate legal advice usually requires document review and confirmed facts.",
        },
        {
          question: "What documents are needed to file a case?",
          answer: "It depends on the case, but usually includes ID, contracts or correspondence, financial evidence, notices, and documents proving the claim.",
        },
        {
          question: "Is settlement better than going to court?",
          answer: "Settlement may save time and cost and preserve business relationships, but the decision depends on evidence strength and the other party’s position.",
        },
        {
          question: "When do I need a corporate lawyer in Oman?",
          answer: "You may need one for company formation, adding a partner, drafting commercial contracts, regulatory review, or shareholder disputes.",
        },
        {
          question: "How can I recover a debt or unpaid amount?",
          answer: "Start by collecting invoices, contracts, and correspondence. A legal notice, claim, or enforcement path can then be assessed.",
        },
        {
          question: "Is website content legal advice?",
          answer: "No. The content is general information only and does not create a lawyer-client relationship unless the firm accepts representation in writing.",
        },
        {
          question: "What is the difference between legal advice and court representation?",
          answer: "Legal advice explains your position, options, and risks. Court representation includes preparing the file, submissions, hearings, and procedural follow-up.",
        },
        {
          question: "Do I need a lawyer before signing a lease or property sale contract?",
          answer: "Contract review is recommended to check authority, property description, obligations, payment terms, termination, and compensation for breach.",
        },
        {
          question: "How should I deal with a bounced cheque in Oman?",
          answer: "Keep the original cheque, bank notice, and correspondence, then assess the suitable legal path for claiming the amount or taking available action.",
        },
        {
          question: "How long do court cases take in Oman?",
          answer: "Timelines vary by case type, parties, documents, expert evidence, and appeals. A lawyer can give an initial estimate after reviewing the file.",
        },
        {
          question: "Can a commercial dispute be resolved without filing a case?",
          answer: "Yes. Negotiation, legal notices, mediation, or settlement can be useful, especially when the parties want to preserve a business relationship.",
        },
        {
          question: "When do I need a legal notice?",
          answer: "A legal notice can record a claim, request performance, or give the other party a final opportunity before formal legal action.",
        },
        {
          question: "What are an employee’s rights when employment is terminated?",
          answer: "Rights depend on contract type, reason for termination, service period, and unpaid dues. The contract, salary records, and correspondence should be reviewed.",
        },
        {
          question: "What should I do if I am dismissed from work?",
          answer: "Keep the termination letter, employment contract, salary records, and related messages, then request a legal assessment of available options.",
        },
        {
          question: "How can I protect my trademark in Oman?",
          answer: "Start with a search for similar marks, submit the right registration application, and keep evidence of use to address objections or infringement.",
        },
        {
          question: "Can contracts be drafted in both Arabic and English?",
          answer: "Yes. The contract can also state which language prevails if there is a conflict. Bilingual drafting helps local and international transactions.",
        },
        {
          question: "Why is a shareholders’ agreement important?",
          answer: "It regulates management, profit distribution, share transfers, exit rights, and dispute handling before disagreements become costly.",
        },
        {
          question: "How do I handle a dispute between business partners?",
          answer: "Review the constitutional documents, shareholders’ agreement, correspondence, and financial decisions, then assess negotiation, settlement, or litigation.",
        },
        {
          question: "Is arbitration suitable for every commercial dispute?",
          answer: "Not always. Arbitration can suit large or specialised contracts, but it requires a clear clause and assessment of cost, time, and enforceability.",
        },
        {
          question: "What does judgment enforcement mean?",
          answer: "Judgment enforcement is the stage of requiring the losing party to comply with the judgment through enforcement procedures and legal safeguards.",
        },
        {
          question: "Can a court judgment be challenged?",
          answer: "There are usually specific challenge routes and deadlines, such as appeal depending on the judgment type. The date and reasoning should be reviewed quickly.",
        },
        {
          question: "What are landlord and tenant rights when rent is late?",
          answer: "Rights depend on the lease, notices, and unpaid amounts. Claims and termination options should be documented and reviewed carefully.",
        },
        {
          question: "Does an expatriate need a lawyer for cases in Oman?",
          answer: "An expatriate may need a lawyer to understand procedure, language, and documents, especially in employment, contracts, family, or financial claims.",
        },
        {
          question: "What is the first step in child custody cases?",
          answer: "The first step is identifying the claims, collecting documents about the children, maintenance, housing, and care, then assessing court or settlement options.",
        },
        {
          question: "How should I prepare my file before meeting a lawyer?",
          answer: "Organise the facts chronologically, collect contracts, messages, receipts, and previous judgments, and write down the key questions you need answered.",
        },
        {
          question: "Can you review a contract sent by a foreign company?",
          answer: "Yes. It can be reviewed for obligations on the Omani party, governing law, jurisdiction, payment, confidentiality, and termination.",
        },
        {
          question: "What is the first step to establish a company in Oman?",
          answer: "Start by identifying the activity, partners, and suitable legal form, then review regulatory requirements and core documents before registration.",
        },
        {
          question: "What is the best legal structure for a new company?",
          answer: "The right structure depends on partners, activity, liability, capital, and expansion plans. It should be assessed before registration.",
        },
        {
          question: "Do I need a shareholders’ agreement if the company is between relatives or friends?",
          answer: "Yes. Personal trust is not enough. A shareholders’ agreement regulates management, profits, exit, death of a partner, and dispute resolution.",
        },
        {
          question: "What clauses matter most in a business partnership agreement?",
          answer: "Important clauses include capital, management, authority, profit distribution, non-compete, confidentiality, withdrawal, and dispute resolution.",
        },
        {
          question: "When does a company need ongoing legal counsel?",
          answer: "A company may need ongoing counsel when it has repeated contracts, employees, suppliers, debts, expansion plans, or decisions needing regular risk review.",
        },
        {
          question: "How can a lawyer protect a company from commercial disputes?",
          answer: "A lawyer helps draft clear contracts, document decisions, create internal policies, review risks, and intervene early before disputes escalate.",
        },
        {
          question: "What documents are needed for a company legal review?",
          answer: "Common documents include commercial registration, constitutional documents, shareholders’ agreement, licences, main contracts, employment contracts, financial obligations, and key correspondence.",
        },
        {
          question: "Should a company review a supply contract before signing?",
          answer: "Yes. Supply contracts often involve delivery dates, quality, warranties, delay penalties, payment terms, and liability for breach.",
        },
        {
          question: "How should a company handle a client who does not pay?",
          answer: "Collect invoices, the contract, purchase orders, and correspondence, then send a demand or legal notice and assess recovery or settlement options.",
        },
        {
          question: "Why do online businesses need terms and conditions?",
          answer: "Terms and conditions clarify sales, payment, returns, liability, privacy, and dispute handling, reducing misunderstandings with customers.",
        },
        {
          question: "Do startups need a lawyer from the beginning?",
          answer: "Early legal support helps protect intellectual property, regulate founder relationships, review investment, and draft customer and supplier contracts.",
        },
        {
          question: "How is a partner exit handled?",
          answer: "The constitutional documents and shareholders’ agreement should be reviewed to determine valuation, share transfer, obligations, confidentiality, and post-exit restrictions.",
        },
        {
          question: "What should be reviewed before accepting a new investor?",
          answer: "Review company valuation, share percentage, voting rights, management, founder obligations, exit terms, and protection of confidential information.",
        },
        {
          question: "Can a company standardise contract templates to reduce risk?",
          answer: "Yes. Standard templates for sales, supply, services, employment, and confidentiality reduce errors and speed up transactions.",
        },
        {
          question: "When does a company need written internal policies?",
          answer: "Written policies are useful when the company has employees, repeated operations, sensitive data, or financial authority that must be clear and enforceable.",
        },
        {
          question: "How can a company protect trade secrets?",
          answer: "Trade secrets can be protected through NDAs, restricted access, internal policies, and clear clauses in employee and supplier contracts.",
        },
        {
          question: "What are the risks of signing a commercial contract without legal review?",
          answer: "Risks may appear in liability, penalties, jurisdiction, termination, payment, or unclear obligations, and may be difficult to change after signing.",
        },
        {
          question: "Can a lawyer attend commercial negotiations?",
          answer: "Yes. A lawyer can protect the legal position during negotiation and document key points before they become a final contract.",
        },
        {
          question: "What legal services do small businesses usually need?",
          answer: "Small businesses often need employment contracts, customer and supplier contracts, debt recovery, trademark protection, and dispute advice.",
        },
        {
          question: "How can legal advice support company growth?",
          answer: "Good legal advice reduces risk, clarifies obligations, improves contracts, and protects the company during expansion or new partnerships.",
        },
      ],
    },
  },
};
