export const siteData = {
  ar: {
    meta: {
      title: "مكتب حسين الراشدي للمحاماة والاستشارات القانونية",
      description: "خدمات قانونية واستشارية ثنائية اللغة للأفراد والشركات داخل سلطنة عمان.",
    },
    firm: {
      ar: "مكتب حسين الراشدي للمحاماة والاستشارات القانونية",
      en: "Hussein Al Rashdi Law Firm & Legal Consultancy",
    },
    common: { menu: "القائمة", close: "إغلاق" },
    nav: {
      home: "الرئيسية",
      cta: "احجز استشارة",
      items: [
        { label: "الرئيسية", href: "#/" },
        { label: "من نحن", href: "#about" },
        { label: "خدماتنا", href: "#services" },
        { label: "فريقنا", href: "#/team" },
        { label: "القطاعات", href: "#sectors" },
        { label: "المعرفة القانونية", href: "#insights" },
        { label: "اتصل بنا", href: "#/contact" },
      ],
    },
    hero: {
      eyebrow: "سلطنة عمان",
      title: "حلول قانونية راسخة، بثقة تمتد أبعد",
      text: "نقدّم استشارات وتمثيلا قانونيا احترافيا للأفراد والشركات داخل سلطنة عمان، بمنهج يجمع بين الدقة القانونية والفهم العملي لاحتياجات العميل.",
      primary: "احجز استشارة",
      secondary: "تعرّف على خدماتنا",
      trust: ["خبرة قانونية", "سرية تامة", "التزام مهني"],
    },
    about: {
      eyebrow: "عن المكتب",
      title: "قانونيون يعرفون عمان ويصغون للعميل",
      imageAlt: "تفاصيل معمارية عمانية",
      text: "يعمل مكتب حسين الراشدي للمحاماة والاستشارات القانونية على تقديم حلول قانونية واضحة وواقعية مبنية على النزاهة، السرية، والمعرفة الدقيقة بالأنظمة والإجراءات في سلطنة عمان. نساند العملاء في القضايا الحساسة والمعاملات اليومية، ونحرص على أن تكون كل خطوة قانونية مفهومة وقابلة للتنفيذ.",
      values: [
        { title: "النزاهة المهنية", text: "رأي قانوني مستقل وشفاف يحمي مصلحة العميل." },
        { title: "الحلول العملية", text: "استراتيجيات قانونية قابلة للتطبيق وليست مجرد آراء نظرية." },
        { title: "السرية والثقة", text: "تعامل مسؤول مع المعلومات والوثائق في كل مرحلة." },
      ],
    },
    services: {
      eyebrow: "خدماتنا",
      title: "مجالات ممارسة قانونية متكاملة",
      text: "بطاقات الخدمات قابلة للتوسعة لتقديم نبذة عملية عن نطاق كل خدمة.",
      items: [
        { icon: "gavel", title: "التقاضي والمرافعات", summary: "تمثيل أمام المحاكم والجهات المختصة.", detail: "إعداد المذكرات، متابعة الإجراءات، إدارة ملفات النزاع، وتمثيل العملاء في الدعاوى المدنية والتجارية والإدارية وفق الأنظمة المعمول بها." },
        { icon: "building", title: "قانون الشركات والاستثمار", summary: "تأسيس، حوكمة، شراكات واستثمار.", detail: "مساندة الشركات في التأسيس، تعديل العقود، تنظيم الشراكات، مراجعة الالتزامات النظامية، وهيكلة الاستثمارات بطريقة تقلل المخاطر." },
        { icon: "contract", title: "العقود والاتفاقيات", summary: "صياغة ومراجعة وتفاوض.", detail: "صياغة عقود دقيقة باللغتين العربية والإنجليزية، مراجعة بنود المسؤولية، إنهاء التعاقد، السرية، والجزاءات، مع دعم التفاوض التجاري." },
        { icon: "home", title: "العقارات والتطوير العقاري", summary: "حماية الصفقات والمشاريع العقارية.", detail: "مراجعة عقود البيع والإيجار، التطوير، المقاولات، الرهن، والتسجيل، ومساندة العملاء في المنازعات أو التسويات العقارية." },
        { icon: "handshake", title: "التحكيم وتسوية المنازعات", summary: "حلول بديلة فعّالة للنزاعات.", detail: "تقييم فرص التسوية، إعداد استراتيجيات التحكيم والوساطة، وتمثيل الأطراف في إجراءات تسوية المنازعات التجارية." },
        { icon: "users", title: "قانون العمل والعمال", summary: "استشارات للمنشآت والأفراد.", detail: "إعداد لوائح وسياسات العمل، مراجعة العقود، التعامل مع المنازعات العمالية، وإنهاء العلاقة التعاقدية بما يحفظ الحقوق." },
        { icon: "family", title: "الأحوال الشخصية والإرث", summary: "قضايا الأسرة والتركات بسرية.", detail: "دعم قانوني في مسائل الزواج والطلاق والنفقة والحضانة والميراث، مع مراعاة حساسية النزاع وخصوصية الأسرة." },
        { icon: "ip", title: "الملكية الفكرية والعلامات التجارية", summary: "حماية الأصول غير الملموسة.", detail: "استشارات حول تسجيل العلامات، التنازل والترخيص، حماية المحتوى التجاري، ومعالجة التعدي أو الاستخدام غير المصرح به." },
        { icon: "debt", title: "تحصيل الديون والتنفيذ", summary: "متابعة المطالبات والتنفيذ.", detail: "إدارة المطالبات المالية، الإنذارات القانونية، أوامر الأداء، ومتابعة إجراءات التنفيذ وفق مسار مهني يحفظ العلاقة حيثما أمكن." },
        { icon: "government", title: "الاستشارات القانونية للجهات الحكومية والخاصة", summary: "رأي مؤسسي واضح وقابل للتنفيذ.", detail: "تقديم مذكرات قانونية، مراجعة سياسات داخلية، تقييم مخاطر تعاقدية وتنظيمية، ودعم اتخاذ القرار للجهات والمؤسسات." },
      ],
    },
    why: {
      eyebrow: "لماذا نحن",
      title: "حضور قانوني هادئ وحاسم",
      text: "نعمل بمنهج يوازن بين حماية الموقف القانوني وسرعة القرار العملي.",
      items: [
        "فهم عميق للبيئة القانونية العمانية",
        "تواصل واضح وشفاف مع العميل",
        "حلول استراتيجية قابلة للتنفيذ",
        "تمثيل احترافي أمام الجهات المختصة",
        "التزام كامل بسرية المعلومات",
      ],
    },
    team: {
      eyebrow: "فريقنا",
      title: "خبرات قانونية متعددة في فريق واحد",
      pageTitle: "Meet Our Team",
      text: "محتوى الفريق محفوظ في ملف بيانات واحد لتسهيل التعديل والتوسعة.",
      pageText: "ملفات تعريفية قابلة للتحديث تشمل الاسم، المنصب، التخصص، وروابط التواصل المهنية.",
      pageCta: "Meet Our Team",
      members: [
        { initials: "ح ر", name: "حسين الراشدي", title: "المؤسس والمحامي الرئيسي", specialty: "التقاضي التجاري، العقود، والاستشارات الاستراتيجية.", linkedin: "https://www.linkedin.com/" },
        { initials: "س ع", name: "سارة العبرية", title: "مستشارة قانونية", specialty: "قانون الشركات، الاستثمار، والحوكمة.", linkedin: "https://www.linkedin.com/" },
        { initials: "م ب", name: "محمد البلوشي", title: "محام مشارك", specialty: "العقارات، العمل، وتسوية المنازعات.", linkedin: "https://www.linkedin.com/" },
        { initials: "ن ح", name: "نورة الحارثية", title: "باحثة قانونية", specialty: "الأحوال الشخصية، التنفيذ، والتحضير الإجرائي.", linkedin: "https://www.linkedin.com/" },
      ],
    },
    sectors: {
      eyebrow: "القطاعات",
      title: "نخدم قطاعات اقتصادية متنوعة",
      text: "نكيّف الرأي القانوني مع واقع القطاع، حجم المخاطر، وسرعة القرار المطلوبة.",
      items: ["العقار", "الإنشاءات", "البنوك والتمويل", "الطاقة", "التجارة", "الشركات العائلية", "التقنية", "الضيافة والسياحة"],
    },
    insights: {
      eyebrow: "المعرفة القانونية",
      title: "رؤى قانونية قابلة للبحث والتوسعة",
      text: "قسم جاهز للربط لاحقا بنظام إدارة محتوى، مع بحث وفلاتر تصنيف.",
      search: "ابحث في المقالات والأسئلة القانونية",
      categories: [
        { key: "all", label: "الكل" },
        { key: "articles", label: "مقالات" },
        { key: "updates", label: "تحديثات" },
        { key: "faq", label: "أسئلة شائعة" },
      ],
      articles: [
        { category: "articles", categoryLabel: "مقال", title: "ما الذي يجب مراجعته قبل توقيع عقد تجاري في عمان؟", excerpt: "نقاط عملية حول الصلاحيات، الالتزامات، الجزاءات، وآليات تسوية النزاع قبل الالتزام بالعقد.", date: "2026" },
        { category: "updates", categoryLabel: "تحديث قانوني", title: "حوكمة الشركات العائلية: من الاتفاق الودي إلى وثيقة ملزمة", excerpt: "أهمية تنظيم الإدارة والملكية والخلافة لحماية استمرارية الشركات العائلية.", date: "2026" },
        { category: "faq", categoryLabel: "سؤال شائع", title: "متى تكون التسوية أفضل من التقاضي؟", excerpt: "تقييم التكلفة، الوقت، الأدلة، والعلاقة التجارية قبل اختيار المسار الأنسب.", date: "2026" },
      ],
    },
    cta: {
      title: "هل تحتاج إلى رأي قانوني موثوق؟",
      text: "دعنا نفهم قضيتك ونرسم الخطوة القانونية المناسبة بسرية ووضوح.",
      button: "طلب استشارة",
    },
    contact: {
      eyebrow: "اتصل بنا",
      title: "احجز استشارة قانونية",
      text: "النموذج جاهز للربط مع Formspree. استبدل رابط الإرسال في الكود قبل استقبال الطلبات الفعلية.",
      fields: [
        { name: "name", type: "text", label: "الاسم الكامل" },
        { name: "phone", type: "tel", label: "رقم الهاتف" },
        { name: "email", type: "email", label: "البريد الإلكتروني" },
        { name: "service", type: "select", label: "نوع الخدمة" },
        { name: "message", type: "textarea", label: "الرسالة" },
      ],
      notice: "جميع المعلومات المرسلة تعامل بسرية تامة.",
      submit: "إرسال الطلب",
      whatsapp: "تواصل عبر واتساب",
      whatsappNumber: "96894953638",
      whatsappMessage: "مرحبا، أرغب في حجز استشارة قانونية مع مكتب حسين الراشدي للمحاماة.",
      addressLabel: "العنوان",
      address: "مسقط، سلطنة عمان - العنوان التفصيلي قابل للتعديل",
      phoneLabel: "الهاتف",
      phone: "+968 9495 3638",
      emailLabel: "البريد الإلكتروني",
      email: "hussaiinlaw@gmail.com",
      hoursLabel: "ساعات العمل",
      hours: "الأحد - الخميس، 8:30 صباحا - 5:00 مساء",
      map: "خريطة تفاعلية قابلة للإضافة",
    },
    footer: {
      text: "مكتب محاماة واستشارات قانونية يقدم دعما مهنيا للأفراد والشركات داخل سلطنة عمان.",
      navTitle: "الروابط",
      practiceTitle: "الخدمات",
      connectTitle: "التواصل",
      privacy: "سياسة الخصوصية",
      terms: "شروط الاستخدام",
      copy: "© 2026 مكتب حسين الراشدي للمحاماة والاستشارات القانونية. جميع الحقوق محفوظة.",
    },
    privacy: {
      title: "سياسة الخصوصية",
      paragraphs: [
        "نحترم خصوصية زوار الموقع ونتعامل مع المعلومات المرسلة عبر نموذج التواصل بسرية.",
        "لا يعالج هذا الموقع أو يخزن البيانات محليا. عند تفعيل Formspree أو أي مزود نماذج آخر، تخضع البيانات لشروط ذلك المزود.",
        "إرسال المعلومات عبر الموقع لا ينشئ علاقة محام وموكل إلا بعد قبول المكتب للتمثيل كتابيا.",
      ],
    },
    terms: {
      title: "شروط الاستخدام",
      paragraphs: [
        "المحتوى المنشور في هذا الموقع لأغراض تعريفية عامة ولا يعد استشارة قانونية.",
        "ينبغي طلب رأي قانوني متخصص قبل اتخاذ أي إجراء بناء على المعلومات المنشورة.",
        "جميع النصوص والهوية البصرية قابلة للتعديل بما يتوافق مع بيانات المكتب النهائية.",
      ],
    },
    social: { linkedin: "https://www.linkedin.com/" },
  },
  en: {
    meta: {
      title: "Hussein Al Rashdi Law Firm & Legal Consultancy",
      description: "Bilingual legal representation and advisory services for individuals and businesses in Oman.",
    },
    firm: {
      ar: "مكتب حسين الراشدي للمحاماة والاستشارات القانونية",
      en: "Hussein Al Rashdi Law Firm & Legal Consultancy",
    },
    common: { menu: "Menu", close: "Close" },
    nav: {
      home: "Home",
      cta: "Book a Consultation",
      items: [
        { label: "Home", href: "#/" },
        { label: "About", href: "#about" },
        { label: "Services", href: "#services" },
        { label: "Team", href: "#/team" },
        { label: "Sectors", href: "#sectors" },
        { label: "Legal Insights", href: "#insights" },
        { label: "Contact", href: "#/contact" },
      ],
    },
    hero: {
      eyebrow: "Sultanate of Oman",
      title: "Grounded legal solutions, trusted beyond the matter",
      text: "We provide professional legal advice and representation for individuals and companies in Oman, combining legal precision with practical understanding of each client’s goals.",
      primary: "Book a Consultation",
      secondary: "Explore Services",
      trust: ["Legal experience", "Complete confidentiality", "Professional commitment"],
    },
    about: {
      eyebrow: "About the firm",
      title: "Oman-focused counsel with a client-centred approach",
      imageAlt: "Omani architectural detail",
      text: "Hussein Al Rashdi Law Firm & Legal Consultancy delivers clear, practical legal solutions rooted in integrity, confidentiality, and knowledge of Omani laws and procedures. We support clients through sensitive disputes and everyday transactions, making each legal step understandable and actionable.",
      values: [
        { title: "Professional Integrity", text: "Independent and transparent legal advice focused on client interests." },
        { title: "Practical Solutions", text: "Strategies designed to work in real negotiations, filings, and disputes." },
        { title: "Confidential Trust", text: "Responsible handling of information and documents at every stage." },
      ],
    },
    services: {
      eyebrow: "Practice Areas",
      title: "Integrated legal services",
      text: "Each service card expands into a concise scope overview for future dedicated pages.",
      items: [
        { icon: "gavel", title: "Litigation and Advocacy", summary: "Representation before courts and competent authorities.", detail: "Pleadings, procedural management, dispute files, and representation in civil, commercial, and administrative matters." },
        { icon: "building", title: "Corporate and Investment Law", summary: "Formation, governance, partnerships, and investment.", detail: "Support for company formation, contract amendments, partnerships, regulatory obligations, and investment structuring." },
        { icon: "contract", title: "Contracts and Agreements", summary: "Drafting, review, and negotiation.", detail: "Precise Arabic and English contracts covering liability, termination, confidentiality, penalties, and negotiation support." },
        { icon: "home", title: "Real Estate and Development", summary: "Protecting property transactions and projects.", detail: "Sale, lease, development, construction, mortgage, registration, and real estate dispute support." },
        { icon: "handshake", title: "Arbitration and Dispute Resolution", summary: "Efficient alternatives to litigation.", detail: "Settlement assessment, arbitration and mediation strategy, and representation in commercial dispute resolution." },
        { icon: "users", title: "Employment and Labour Law", summary: "Advice for employers and individuals.", detail: "Policies, employment contracts, labour disputes, and termination processes designed to preserve rights." },
        { icon: "family", title: "Personal Status and Inheritance", summary: "Family and estate matters handled discreetly.", detail: "Support in marriage, divorce, maintenance, custody, and inheritance matters with sensitivity and confidentiality." },
        { icon: "ip", title: "Intellectual Property and Trademarks", summary: "Protection for intangible business assets.", detail: "Trademark registration, licensing, assignment, commercial content protection, and infringement response." },
        { icon: "debt", title: "Debt Recovery and Enforcement", summary: "Claims and enforcement follow-up.", detail: "Financial claims, legal notices, payment orders, and enforcement procedures conducted professionally." },
        { icon: "government", title: "Legal Advisory for Public and Private Entities", summary: "Institutional advice that can be implemented.", detail: "Legal memoranda, internal policy review, contractual and regulatory risk assessment, and decision support." },
      ],
    },
    why: {
      eyebrow: "Why choose us",
      title: "Calm, decisive legal presence",
      text: "Our method balances legal protection with practical decision-making.",
      items: [
        "Deep understanding of the Omani legal environment",
        "Clear and transparent client communication",
        "Strategic solutions ready for implementation",
        "Professional representation before competent authorities",
        "Full commitment to confidentiality",
      ],
    },
    team: {
      eyebrow: "Our team",
      title: "A multidisciplinary legal team",
      pageTitle: "Meet Our Team",
      text: "All team content is maintained in a single editable data file.",
      pageText: "Profiles include names, titles, specialty lines, and professional links ready for future editing.",
      pageCta: "Meet Our Team",
      members: [
        { initials: "HR", name: "Hussein Al Rashdi", title: "Founder and Principal Lawyer", specialty: "Commercial litigation, contracts, and strategic advisory.", linkedin: "https://www.linkedin.com/" },
        { initials: "SA", name: "Sara Al Abri", title: "Legal Consultant", specialty: "Corporate law, investment, and governance.", linkedin: "https://www.linkedin.com/" },
        { initials: "MB", name: "Mohammed Al Balushi", title: "Associate Lawyer", specialty: "Real estate, labour law, and dispute settlement.", linkedin: "https://www.linkedin.com/" },
        { initials: "NH", name: "Noura Al Harthi", title: "Legal Researcher", specialty: "Personal status, enforcement, and procedural preparation.", linkedin: "https://www.linkedin.com/" },
      ],
    },
    sectors: {
      eyebrow: "Sectors",
      title: "Serving a range of economic sectors",
      text: "We adapt legal advice to the sector’s realities, risk profile, and pace of decision-making.",
      items: ["Real estate", "Construction", "Banking and finance", "Energy", "Trade", "Family businesses", "Technology", "Hospitality and tourism"],
    },
    insights: {
      eyebrow: "Legal Insights",
      title: "Searchable and future-ready knowledge",
      text: "A clean section ready to connect to a CMS later, with search and category filters already in place.",
      search: "Search articles, updates, and legal FAQs",
      categories: [
        { key: "all", label: "All" },
        { key: "articles", label: "Articles" },
        { key: "updates", label: "Updates" },
        { key: "faq", label: "FAQs" },
      ],
      articles: [
        { category: "articles", categoryLabel: "Article", title: "What should you review before signing a commercial contract in Oman?", excerpt: "Practical points on authority, obligations, remedies, and dispute resolution before committing.", date: "2026" },
        { category: "updates", categoryLabel: "Legal update", title: "Family business governance: from informal agreement to binding document", excerpt: "Why ownership, management, and succession rules help preserve continuity.", date: "2026" },
        { category: "faq", categoryLabel: "FAQ", title: "When is settlement better than litigation?", excerpt: "A look at cost, timing, evidence, and commercial relationships before choosing a path.", date: "2026" },
      ],
    },
    cta: {
      title: "Need a trusted legal opinion?",
      text: "Let us understand your matter and shape the right next legal step with clarity and confidentiality.",
      button: "Request a Consultation",
    },
    contact: {
      eyebrow: "Contact",
      title: "Book a legal consultation",
      text: "The form is ready for Formspree. Replace the editable endpoint in the code before accepting real enquiries.",
      fields: [
        { name: "name", type: "text", label: "Full name" },
        { name: "phone", type: "tel", label: "Phone number" },
        { name: "email", type: "email", label: "Email address" },
        { name: "service", type: "select", label: "Service type" },
        { name: "message", type: "textarea", label: "Message" },
      ],
      notice: "All submitted information is treated with complete confidentiality.",
      submit: "Send request",
      whatsapp: "WhatsApp us",
      whatsappNumber: "96894953638",
      whatsappMessage: "Hello, I would like to book a legal consultation with Hussein Al Rashidi Law Firm.",
      addressLabel: "Office address",
      address: "Muscat, Sultanate of Oman - detailed address editable",
      phoneLabel: "Phone",
      phone: "+968 9495 3638",
      emailLabel: "Email",
      email: "hussaiinlaw@gmail.com",
      hoursLabel: "Working hours",
      hours: "Sunday - Thursday, 8:30 AM - 5:00 PM",
      map: "Interactive map placeholder",
    },
    footer: {
      text: "A law firm and legal consultancy serving individuals and businesses in the Sultanate of Oman.",
      navTitle: "Navigation",
      practiceTitle: "Practice areas",
      connectTitle: "Connect",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
      copy: "© 2026 Hussein Al Rashdi Law Firm & Legal Consultancy. All rights reserved.",
    },
    privacy: {
      title: "Privacy Policy",
      paragraphs: [
        "We respect visitor privacy and treat information submitted through the contact form confidentially.",
        "This website does not process or store data locally. Once Formspree or another provider is enabled, submitted data is subject to that provider’s terms.",
        "Submitting information through this site does not create a lawyer-client relationship unless the firm accepts representation in writing.",
      ],
    },
    terms: {
      title: "Terms of Use",
      paragraphs: [
        "The content on this website is general information and does not constitute legal advice.",
        "You should seek specific legal advice before acting on any information published here.",
        "All copy and brand details are editable to match the firm’s final approved information.",
      ],
    },
    social: { linkedin: "https://www.linkedin.com/" },
  },
};
